DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Tasks;
DROP TABLE IF EXISTS Sessions;
DROP TABLE IF EXISTS Attendees;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Requests;
DROP TABLE IF EXISTS Assignees;

CREATE TABLE Users(
    UserID INTEGER NOT NULL PRIMARY KEY,
    Username VARCHAR(20) NOT NULL UNIQUE,
    Email VARCHAR(50) UNIQUE,
    PasswordHash CHAR(64) NOT NULL,
    Formation VARCHAR(40),
    Institution VARCHAR(40),
    StyleColor VARCHAR(20) NOT NULL
);

CREATE TABLE Groups(
    GroupID INTEGER NOT NULL PRIMARY KEY,
    OwnerID INTEGER NOT NULL ,
    Name VARCHAR(30) NOT NULL,
    Subject VARCHAR(30),
    Description VARCHAR(200),
    IsPrivate BOOLEAN NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    StudyLevel VARCHAR(30) NOT NULL DEFAULT "High School",
    StyleColor VARCHAR(20) NOT NULL,
    FOREIGN KEY (OwnerID) REFERENCES Users(UserID)
);
CREATE TABLE Tasks(
    TaskID INTEGER NOT NULL PRIMARY KEY,
    GroupID INTEGER NOT NULL ,
    Name VARCHAR(30) NOT NULL,
    Description VARCHAR(200),
    DueDateTime DATETIME(0),
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID)
);
CREATE TABLE Sessions(
    SessionID INTEGER NOT NULL PRIMARY KEY,
    GroupID INTEGER NOT NULL ,
    Name VARCHAR(30) NOT NULL,
    Location VARCHAR(30) NOT NULL,
    Description VARCHAR(200),
    Date DATE Not NULL,
    StartTime TIME(0) NOT NULL,
    EndTime TIME(0) NOT NULL,
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID)
);
CREATE TABLE Attendees(
    UserID INTEGER NOT NULL,
    SessionID INTEGER NOT NULL,
    PRIMARY KEY (UserID,SessionID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (SessionID) REFERENCES Sessions(SessionID));
CREATE TABLE Assignees(
    UserID INTEGER NOT NULL,
    TaskID INTEGER NOT NULL,
    TaskStatus VARCHAR(20) NOT NULL,
    PRIMARY KEY (UserID,TaskID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID)
);
CREATE TABLE Members(
    UserID INTEGER NOT NULL ,
    GroupID INTEGER NOT NULL ,
    Role VARCHAR(6) NOT NULL DEFAULT "Member",
    PRIMARY KEY (UserID,GroupID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID)
);
CREATE TABLE Requests(
    UserID INTEGER NOT NULL,
    GroupID INTEGER NOT NULL ,
    PRIMARY KEY (UserID,GroupID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GroupID) REFERENCES Groups(GroupID)
);